recipe: default.v1
language: "en"  # Default language: English
additional_languages:
  - "it"   # Italian
  - "de"   # German
  - "fr"   # French
pipeline:
  - name: NLUCommandAdapter
  - name: custom.compact_llm_command_generator_override_component.CustomCompactLLMCommandGenerator
    prompt_template: data/prompts/command_prompt_v3_gpt_4o_2024_11_20_template.jinja2
    llm:
      model_group: command_generator_model_group
    user_input:
      max_characters: 2000
    flow_retrieval:
      embeddings:
        model_group: embedding_model_group
      num_flows: 15

policies:
  - name: FlowPolicy
#  - name: rasa_plus.ml.DocsearchPolicy
  - name: RulePolicy
assistant_id: sam-voice

