recipe: default.v1
language: "de"  # Default language: German
additional_languages:
  - "it"   # Italian
  - "en"   # English
  - "fr"   # French
pipeline:
  - name: LLMBasedRouter
    calm_entry:
      sticky: "handles everything else, including finance, doctor appointments and pizza orders"
    nlu_entry:
      sticky: "handles only health advice, hotel reservations and restaurant bookings"
      non_sticky: "handles chitchat"
  - name: NLUCommandAdapter
  - name: custom.compact_llm_command_generator_override_component.CustomCompactLLMCommandGenerator
    llm:
      model_group: command_generator_model_group
    user_input:
      max_characters: 2000
    flow_retrieval:
      embeddings:
        model_group: embedding_model_group
      num_flows: 15

policies:
  - name: FlowPolicy
#  - name: rasa_plus.ml.DocsearchPolicy
  - name: RulePolicy
assistant_id: sam-voice

